version: 2
defaults: &defaults
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Check docker is running
          command: docker info
      - run:
          name: Pull Community Hass.io Add-ons build environment
          command: docker pull hassioaddons/build-env:latest
      - run:
          name: Log in to Docker Hub
          command: |
            if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
            then
              docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            fi
      - checkout
      - deploy:
          name: Build and (maybe) deploy
          command: |
              if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
              then
                docker run \
                  --privileged \
                  -v ~/.docker:/root/.docker \
                  -v "$PWD":/docker \
                  hassioaddons/build-env:latest \
                  --image "hassioaddons/pi-hole-{arch}" \
                  --git \
                  --target pi-hole \
                  --${ARCH} \
                  --push
              else
                docker run \
                  --privileged \
                  -v "$PWD":/docker \
                  hassioaddons/build-env:latest \
                  --image "hassioaddons/pi-hole-{arch}" \
                  --git \
                  --target pi-hole \
                  --${ARCH}
              fi
      - deploy:
          name: Send notification to Microbadger
          command: |
              if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
              then
                curl -X POST https://hooks.microbadger.com/images/${MICROBADGER_WEBHOOK}
              fi

jobs:
  aarch64:
    <<: *defaults
    environment:
      ARCH: aarch64
      MICROBADGER_WEBHOOK: hassioaddons/pi-hole-aarch64/pXRJSw5ETjOPFwiKxRQkDQuZVXY=
  amd64:
    <<: *defaults
    environment:
      ARCH: amd64
      MICROBADGER_WEBHOOK: hassioaddons/pi-hole-amd64/dW8ZA-Z-HuK9kZJlEdLl5fFrnEw=
  armhf:
    <<: *defaults
    environment:
      ARCH: armhf
      MICROBADGER_WEBHOOK: hassioaddons/pi-hole-armhf/6bdl-V5sP_UANSPGh1Zdn7XOhNA=
  i386:
    <<: *defaults
    environment:
      ARCH: i386
      MICROBADGER_WEBHOOK: hassioaddons/pi-hole-i386/so7sdmmzok409B90kXswRR6NuRA=

workflows:
  version: 2
  build_and_maybe_deploy:
    jobs:
      - aarch64:
          filters:
            tags:
              only: /.*/
      - amd64:
          filters:
            tags:
              only: /.*/
      - armhf:
          filters:
            tags:
              only: /.*/
      - i386:
          filters:
            tags:
              only: /.*/